#!/bin/bash

dir=$(dirname $(readlink -f $0))
cd $dir

minute=$(python -c "import random as r; print r.randrange(60)")
hour=$(python -c "import random as r; print r.randrange(24)")

                                   
(crontab -l 2>/dev/null | grep -v "ARCADE2ics";
 echo "$minute $hour * * * $dir/run_from_arcade.py > /dev/null") | crontab -

echo "Running daily at $hour:$minute."

$dir/run_from_arcade.py
